### PR TITLE
Adding tests for util

### PR DESCRIPTION
**Pull request by simongarisch**

### CODE REVIEW

**Comment by simongarisch** [comment]
Thanks for the heads up there. I've changed some of the tests to also run with python 2.7. I haven't pushed up changes to trade.py yet as I'm making some additional changes there, but instead of the enum we can have:

        if state not in list(vars(TradeState).values()) or state is None:
            raise TradeStateError

This is not as elegant, but it will work under both python 2 and 3. As for the trade.py file more generally I saw that this can be extended with additional logic for shorting and opening / closing positions of different sizes. For example, if we open a position for 100 shares and then a second position again for 100 shares the close position logic doesn't quite operate correctly. You have to open and close the entire position at once rather than gradually. Parts of this are stated in https://github.com/fja05680/pinkfish/issues/3

Are you happy for me to make some changes to the trade.py file (that is backwards compatible) to support this functionality?

Cheers,
Simon.

**Comment by simongarisch** [comment]
I've added only minor changes to trade.py there and some more tests. Those tests should now be passing for Python 2 and 3. I've yet to make changes that support shorting or building into positions.

**Comment by fja05680** [comment]
Hi Simon,

Thanks for all your efforts thus far.  I plan to take a look at least by this weekend.  I appreciate you making small specific commits.  That makes things easier to manage, and is the proper way to use git.  Being able to scale in and out of positions is something that I always planned to add.  If you want to do that, then go for it.  Shorting might be more involved, but it is something I eventually want to have.

Farrell

**Comment by fja05680** [comment]
Simon, I have merge in your changes.  I was able to run the test in Python 2.7.

**Comment by fja05680** [comment]
Simon, unless you have started modifying the code to scale in and out, you may want to wait a bit.  I've made some significant progress in that area now, in no small part because you mentioned it.  I'm also making some speed enhancements.  I plan to have the code posted in a week or so.  If you have already started, Ill certainly take a look at what you have done, and incorporate what I feel is the best parts of both our efforts.

Farrell

**Comment by simongarisch** [comment]
Hi Farrell. Thanks for the heads up. I haven't started on changes for that yet - will be good to see what you have. 

Cheers,
Simon.

**Comment by fja05680** [comment]
Simon,

Finally completed scale-in and scale-out functionality.  Some tests need
updating.  I wasn't able to make it 100% backward compatible.  Actually, I
tried to make the API better.

cheers,
Farrell

**Comment by fja05680** [comment]
Hi Simon,

Finally completed scale-in and scale-out functionality.  Some tests need updating.  I wasn't able to make it 100% backward compatible.  Actually, I tried to make the API better.

cheers,
Farrell

**Comment by simongarisch** [comment]
Sounds good. I’ll take a look.

**Pull request merged**
