### PR TITLE
support fetch_timeseries without modifying the symbols 

### PR DESCRIPTION
**Pull request by andrewvmail**
Fixing below error when using symbols from TSX and ASX. 
Added symbol_as_is parameter to fetch
image

### CODE REVIEW

**Comment by fja05680** [comment]
Thanks for your PR.  I'll look into this over the Christmas break.  Do the symbols from TSX and ASX use underscores?  Is that the issue?  That could cause other problems with using pinkfish.  I would need to look into it.

**Comment by andrewvmail** [comment]
Actually, TSX and ASX symbols uses as is listed in Yahoo Finance uses a period then suffixed with an AX or a TO. 

https://github.com/fja05680/pinkfish/blob/master/pinkfish/fetch.py#L103-L109

These lines will change the symbol will replace the dot into an underscore and it would throw an error.

**Comment by andrewvmail** [comment]
pf.USE_YAHOO_TICKER_SYMBOL instead of the previous approach, less changes to the code base.

**Comment by fja05680** [comment]
Andrew, I decided that the replacement for '.' to '-' doesn't seem to be required anymore, so I just removed that code.  Thanks for pointing out this issue.  Farrell

**Pull request closed without merging**
