### PR TITLE
Added pandas_datareader for yahoo finance data, modified start date (as 1900 can cause errors) and updated deprecated pandas methods

### PR DESCRIPTION
**Pull request by simongarisch**
My previous pull request  was a bit messy, so I've cleaned it up. This is a bit more to the point. Cheers.

### CODE REVIEW

**Comment by fja05680** [comment]
Thanks again for your pull request.  Unfortunately, I've been too busy with
school and work to incorporate your changes.  I'm taking next semester off
and will have more time.  I plan to add more example and some
documentation, and perhaps some new features.

In the mean time, can you tell me which stock symbols were giving you
trouble with dates before 1970?  I want to leave it at 1900 to pull in all
the data.  Some stocks go way back before 1970, e.g. S&P500.  If necessary,
I'd rather add an override so that the user can specify a different start
date for whatever symbols are giving issues.  I also know that yahoo
finance was problematic for a few months and actually briefly went away
altogether.

thanks,
Farrell

**Comment by simongarisch** [comment]
That's all good. It looks like pandas_datareader has been fixed to get data from yahoo finance. However, there looks to be a catch... looking at the code:

import pandas_datareader as pdr
import datetime
symbol = "GOOG"
ts = pdr.DataReader(symbol, "yahoo", start=datetime.date(1971, 1, 1))
print(ts.tail())

This will work fine, but if you put in a year < 1971 you'll get an error unix_start = int(time.mktime(self.start.timetuple())), OverflowError: mktime argument out of range. This looks to be a known issue throwing an error (on Windows):
https://github.com/ranaroussi/fix-yahoo-finance/issues/25
https://github.com/mission-liao/pyswagger/issues/63

I can wrap it up in try... except if you like to attempt 1900 first and then try 1971 if that doesn't work.

Cheers,
Simon.

**Comment by fja05680** [comment]
Simon, I finally got your pull-request committed.  Thanks!  However, I left
out the date change to 1971.  There are stocks that date back older than
that, so I need to leave in the ability to go back as far as possible and
get all the data.  I may add in an additional parameter to fetch that allow
one to specify the start fetch date.  The parameter would default to 1900.

Farrell

**Comment by simongarisch** [comment]
Thanks :-)

**Comment by fja05680** [comment]
FYI:
added the parameter "from_year=1900" to fetch_timeseries()

**Pull request closed without merging**
