### PR TITLE
Should I add more testing or ...

### PR DESCRIPTION
**Pull request by simongarisch**
Afternoon.

I went about setting up my environment, so added a (dev) requirements.txt file and a quick testing script for measuring coverage. I'm happy to extend test coverage if that works for you. I'd be good to have the tests running on travis and perhaps make the install available over pip (under your account). The ta-lib dependency is a bit of a hairy one as there are a few hoops to jump through for the install.

I also ran black code formatting over the repo, but happy to reverse if you don't like it.

Let me know your thoughts.

Cheers,
Simon.

### CODE REVIEW

**Comment by fja05680** [comment]
Simon,

Thank you for your interest in pinkfish and the effort that you have
already put into the project.  I'll need a few days to look over what you
have already done, and familiarize myself with some of the things like
black code formatting which I hadn't heard if before.

Thanks,

Farrell

**Comment by simongarisch** [comment]
Hi there.

Thanks for getting back. I've added some tests for fetch.py. It was mostly good, but I did run into my old issue of https://github.com/fja05680/pinkfish/pull/5

To get around this I've defaulted the from_year as 1971 on Windows and 1900 otherwise. Perhaps I should throw a warning there for Windows users... Happy to be guided by you on how you'd like to approach it. We could set the default back to 1990 for all users too.

**Comment by simongarisch** [comment]
1900!

**Comment by fja05680** [comment]
Simon,
I've reviewed the changes in your pull request.  While I'm impressed with what black code formatting did with the code, I don't like some of the things that it did.  So, I don't want to incorporate that right now.  I like the way you coded around the date issue for windows.  Feel free to add any test you wish.  As far as pip goes, that certainly would lower the barrier for others that want to try pinkfish.  Can you resubmit the first commit without black code formatting?

thanks,
Farrell

**Comment by simongarisch** [comment]
No worries. I'll create a new pull request and clean it up a bit.

**Pull request closed without merging**
